name: Test pipeline
on:
  pull_request:

jobs:
  deploy:
    uses: StanislavZoldak/daipe-test-project/.github/workflows/run_command.yml@sz-test
    with:
      command: daipe dbx:repo:update --env=test --repo-url=${{ github.server_url }}/${{ github.repository }}.git --branch=${{ github.head_ref }} --repo-name=${{ github.head_ref }}
      env: test
    secrets:
      DBX_URL: ${{ secrets.DBX_URL }}
      DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
